name: Today All Sync (Current Day)

on:
  workflow_dispatch:

concurrency:
  group: today-all-sync
  cancel-in-progress: true

jobs:
  run-today-all:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install ODBC driver and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg apt-transport-https unixodbc unixodbc-dev
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run Today Clients ETL
        env:
          MSSQL_DIRECT_CONNECTION: ${{ secrets.MSSQL_DIRECT_CONNECTION }}
          PG_CONNECTION_URL: ${{ secrets.PG_CONNECTION_URL }}
        run: |
          python scripts/etl/run_today_clients.py

      - name: Run Today BO/BI ETL
        env:
          MSSQL_DIRECT_CONNECTION: ${{ secrets.MSSQL_DIRECT_CONNECTION }}
          PG_CONNECTION_URL: ${{ secrets.PG_CONNECTION_URL }}
        run: |
          python scripts/etl/run_today_bo_bi.py