name: Today Clients Sync

on:
  workflow_dispatch:
  # Optionally run automatically
  # schedule:
  #   - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  sync-clients:
    name: Sync Clients Table (Today)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install ODBC Driver for SQL Server
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17
          sudo apt-get install -y unixodbc-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run Today Clients Sync
        env:
          # PHC SQL Server connection
          MSSQL_DIRECT_CONNECTION: ${{ secrets.MSSQL_DIRECT_CONNECTION }}
          
          # Supabase PostgreSQL credentials
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_DB: ${{ secrets.PG_DB }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_PORT: ${{ secrets.PG_PORT }}
          PG_SSLMODE: ${{ secrets.PG_SSLMODE }}
        run: |
          python scripts/etl/run_today_clients.py

      - name: Notify on failure
        if: failure()
        run: |
          echo "::error::Today Clients sync failed. Check logs for details."
